### ISSUE TITLE
Game History Playback Entry Has "Done" button when it should be "Replay" and "Export".

### ISSUE THREAD

**Issue by DLLarson** [CyberBoardPBEM/cbwindows#103] opened 2022-12-14 18:59 UTC
When history entry is activated for playback the associated button shows "Done" when I should show "Replay" and "Export" buttons. If the history entry is single clicked it fixes the buttons. If the history entry is double clicked, the "Done" button is shown again.

![image](https://user-images.githubusercontent.com/175455/207687960-294668ed-f262-46c3-ab2d-fd4b0d23468d.png)

-Dale

**Comment by wsu-cb** [comment] 2022-12-14 19:42
I think I see the same thing in CB 3.1.  Can you verify that both CB 3.1 is doing the same thing, and that this is a bug?

**Comment by wsu-cb** [comment] 2022-12-14 19:51
It looks to me like this only happens with the first history entry.  Since your current .gam has only one entry, it will always happen, but that appears not to be true in general.

**Comment by DLLarson** [comment] 2022-12-14 21:19
> It looks to me like this only happens with the first history entry. Since your current .gam has only one entry, it will always happen, but that appears not to be true in general.

I see the same thing. It looks to be limited to the first item in both versions of the code. There is a difference between the old and new code though. When I double-click the first entry in the new code the "Done" seems to toggle between the proper buttons and improper buttons.

In the old (shipping) code the "Done" only shows up when the first history entry is activated. If the history entry is selected again it corrects itself. After that it stays like it should regardless of how often I double-click it. However the old code has weird "fade in" effect of the enabled "Export" button. That could be caused by how the Windows does auto-scaling for DPI unaware applications.

-Dale

**Comment by wsu-cb** [comment] 2022-12-14 21:34
To be sure I understand what you're saying, do you only see the toggle behavior in the new code with a `.gam` with only one history entry?  I see what I think you mean on a single move `.gam`, but not a "typical" longer history `.gam`.

**Comment by DLLarson** [comment] 2022-12-14 21:58
Actually I can't test the game I have a large history (Tactics 2) with because I'm getting an assert when it's trying to serialize drawing objects with the current master. I'd like to send it to you via Email so you can check it out:

![image](https://user-images.githubusercontent.com/175455/207723569-43d4ef53-41bc-46ff-8335-f217127c1dca.png)

VS's break location:

![image](https://user-images.githubusercontent.com/175455/207723921-6d647805-f52a-4b58-8dbf-9c939742ec69.png)

-Dale

**Comment by wsu-cb** [comment] 2022-12-14 22:35
Test case received, and I reproduce the assert failure.  Investigating ...

**Comment by wsu-cb** [comment] 2022-12-15 03:31
By my reading of the tag `v3.5-prerelease-2` code, `CreateObjectID(CDrawObj::drawMarkObj)` should always create `CMarkObj`s with an object ID of `0x2xxxxxxxx`.  However, the test `.gam` has all of its `CMarkObj`s with object ID of `0x1xxxxxxxx`.  My interpretation of the tag `v3.5-prerelease-2` code is that nothing should have an object ID of `0x1xxxxxxxx`, and I actually added code that checks for invalid IDs, which is what is rejecting this `.gam`. 

So did I misunderstand the legal object ID values, or is this `.gam` somehow corrupt?  For what it's worth, git says this checking was merged to branch `master` in Sep 2021, and I think you have been running some checks of branch `master` against old files since then.  Was this `.gam` one of the test cases?

**Comment by DLLarson** [comment] 2022-12-15 19:19
Hi Bill,

This V3 Tactics 2 game file should never have been upgraded by our work--only the shipping code. So whatever it is should be valid. I have another version that is even older (it's from the 2.x days) that I will send to you. Tactics 2 (the first game ever played with CB) is my go-to test for compatibility breakage.

As far as getting the old school encoding wrong. It's possible we miss-interpreted something. It's be a looooong time since I did this stuff. But one thing is for sure, CB needs to be able to absorb old versions of the files so it appears some more needs to be detected.

Lately I've been investigating the graphics stuff via the debugger and it's been an eye opening experience on all the things I forgot since I brewed it all up. After quite a few hours of spelunking it's only now starting to make some sense. And I've only focused on the CBDesign code to reduce (such that I can) the complexity of my travels.

-Dale

**Comment by DLLarson** [comment] 2022-12-16 22:18
> To be sure I understand what you're saying, do you only see the toggle behavior in the new code with a `.gam` with only one history entry? I see what I think you mean on a single move `.gam`, but not a "typical" longer history `.gam`.

Ok.. I got a chance to check this. When activating entries other than the first, the buttons are fine. What I think is happening is some sort of race condition because on double-click the first history entry is pushed down and the `<History Entry Playback>` line takes its place. That's the line that should have the "Done" button but the history entry is what is selected. If I click the entry it refreshes with the proper buttons.

-Dale

**Closed** 2022-12-17 17:14 UTC
Labels: bug
